# Generated by Django 5.2.17 on 2026-09-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videolike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolike',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'like'), (-1, 'dislike')]),
        ),
    ]
