# Generated by Django 5.2.17 on 2026-09-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_videolike_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolike',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')]),
        ),
    ]
